name: BPB Auto Obfuscation

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 1 * * *'

jobs:
  obfuscate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Download
